### PR TITLE
packet: Fix Typo in IPv4 Address

### PR DESCRIPTION
**Pull request by florianl**
This PR fixes a simple IPv4 Address typo.

Signed-off-by: Florian Lehner <dev@der-flo.net>

### CODE REVIEW

**Comment by aregm** [comment]
Florian, please rebase merge to intel:develop. All new fixes and features go to develop branch and then versioned on the master.

**Comment by gshimansky** [comment]
I believe a fix for the problem was already integrated in 7ab61f47db587ddca1ff943b717d378e15528db9 so this PR may be closed.

**Comment by florianl** [comment]
Sorry, that I did not find 7ab61f4 before.

**Comment by gshimansky** [comment]
It is a recent addition. We fixed the same code in parallel.

**Pull request closed without merging**
