### PR TITLE
Upgrade DPDK to version 18.08

### PR DESCRIPTION
**Pull request by gshimansky**
Patch to update DPDK version. Maybe it helps with #446.

### CODE REVIEW

**Comment by gshimansky** [comment]
Currently there is a problem in port initialization. On VMs error message is 
```
Ethdev port_id=0 invalid rss_hf: 0x3ffffc, valid value: 0x0
```
and on physical systems it is
```
Ethdev port_id=0 invalid rss_hf: 0x3ffffc, valid value: 0x7ef8
```

**Comment by ifilippov** [comment]
VM don't have RSS at all - so it is 0x0.

**Comment by ifilippov** [comment]
You can add
diff --git a/low/low.h b/low/low.h
index b8c7a11..f94af32 100644
--- a/low/low.h
+++ b/low/low.h
@@ -189,7 +189,7 @@ int port_init(uint16_t port, bool willReceive, uint16_t sendQueuesNumber, struct
                                        .mq_mode = ETH_MQ_RX_RSS    },
                .txmode = { .mq_mode = ETH_MQ_TX_NONE, },
                .rx_adv_conf.rss_conf.rss_key = NULL,
-               .rx_adv_conf.rss_conf.rss_hf = ETH_RSS_PROTO_MASK
+               .rx_adv_conf.rss_conf.rss_hf = dev_info.flow_type_rss_offloads
        };

        if (hwtxchecksum) {
to your patch. It should work.

**Comment by aregm** [comment]
> We use RSS ETH_RSS_PROTO_MASK configuration which includes all possible variants like ETH_RSS_IPV4, ETH_RSS_IPV6, ETH_RSS_VXLAN etc. DPDK begins to check the availability of all these features at NIC and looks like some of them are missing.

Even in this case, it should not fail. It should return that feature is unavailable.

**Comment by aregm** [comment]
Waiting for DPDK team to resolve an issue with PktGen...

**Comment by gshimansky** [comment]
Latest patch tested on stability tests with HW acceleration. All stability tests passed.
```
2018/10/03 13:35:05 EXECUTED TEST NAMES: [merge 0 merge 1 merge 2 merge 3 merge 4 merge 5 merge 6 split vector split separate vector separate partition vector partition pcopy handle vector handle dhandle vector dhandle cksums_ipv4_tcp cksums_ipv4_udp cksums_ipv4_icmp cksums_ipv6_tcp cksums_ipv6_udp cksums_ipv6_icmp cksums_ipv4_tcp_vlan cksums_ipv4_udp_vlan cksums_ipv4_icmp_vlan cksums_ipv6_tcp_vlan cksums_ipv6_udp_vlan cksums_ipv6_icmp_vlan]
2018/10/03 13:35:05 PASSED TEST NAMES: [merge 0 merge 1 merge 2 merge 3 merge 4 merge 5 merge 6 split vector split separate vector separate partition vector partition pcopy handle vector handle dhandle vector dhandle cksums_ipv4_tcp cksums_ipv4_udp cksums_ipv4_icmp cksums_ipv6_tcp cksums_ipv6_udp cksums_ipv6_icmp cksums_ipv4_tcp_vlan cksums_ipv4_udp_vlan cksums_ipv4_icmp_vlan cksums_ipv6_tcp_vlan cksums_ipv6_udp_vlan cksums_ipv6_icmp_vlan]
2018/10/03 13:35:05 FAILED TEST NAMES: []
2018/10/03 13:35:05 TESTS EXECUTED: 30
2018/10/03 13:35:05 PASSED: 30
2018/10/03 13:35:05 FAILED: 0
```

**Pull request merged**
