### PR TITLE
Remove mempool problems from tests

### PR DESCRIPTION
**Pull request by ifilippov**
Problems with rte_mempool_free have gone with new DPDK

### CODE REVIEW

**Comment by ifilippov** [comment]
Cannot reproduce https://github.com/intel-go/nff-go/issues/301, remove stuff connected with it.

**Comment by gshimansky** [comment]
> Cannot reproduce #301, remove stuff connected with it.

If you cannot reproduce the bug, can we still run tests separately for every function? I very much prefer it that way than a single test for all functions together.

**Comment by ifilippov** [comment]
These tests are also checked behavior of start stop. It is not our normal stability tests and they don't have any connections with teamcity. So why do you need this?

**Comment by ifilippov** [comment]
It is wrong decision to have these tests separately (you will not be able to check there combines output - only grep for 11 "SUCCESS" words). I leave them separately.

**Pull request merged**
