### PR TITLE
Extracted generator to examples, updated readme, renamded generator

### PR DESCRIPTION
**Pull request by dkolistratova**

### CODE REVIEW

**Comment by dkolistratova** [comment]
#429

**Comment by ifilippov** [comment]
Make clean
Dockerfile

**Comment by ifilippov** [comment]
No root user. Can you please login as Daria Kolistratova

**Comment by ifilippov** [comment]
Can you please remove parseConfig package and add parseConfig file to generator package (as separate file)

**Comment by dkolistratova** [comment]
config parsing  and generation are two completely different entities.

**Pull request merged**
