### PR TITLE
Update latency test, add to test framework

### PR DESCRIPTION
**Pull request by mbulatova**
- Calculate median, average and stddev latency
- Add writing statistics to file
- Modify test system to copy created output file from container to log dir
- Add timout to stabilize speed
- Use FastGenerator
- Remove latency-stub.go as unnecessary (perf_light and others should be
used as part2)
- Add more tests to latency.json
- Add noscheduler flag

### CODE REVIEW

**Comment by mbulatova** [comment]
#291

**Comment by ifilippov** [comment]
Approved, however you should connect with Gregory about test system changes.

**Comment by mbulatova** [comment]
Updated

**Comment by gshimansky** [comment]
That update is good, you got everything right, except that there is no report for latency tests. It is necessary to add a new section to HTML report in report.go and a report_test with a latency test type which you can use to debug the html output.
If you think that is too complex for you, you can commit the current change, and I will add the report part later myself.

**Comment by mbulatova** [comment]
@gshimansky thanks for tips!

**Comment by mbulatova** [comment]
@gshimansky is last commit ok?

**Pull request merged**
