### PR TITLE
Modified style in merge function.

### PR DESCRIPTION
**Pull request by dkolistratova**
suggested by @Quasilyte

### CODE REVIEW

**Comment by Quasilyte** [comment]
I wonder what other team members think about this:
```diff
-func merge(from *low.Ring, to *low.Ring) {
+func merge(from, to *low.Ring) {
```

Type switch change looks like a clear win in terms of readability.

**Comment by ifilippov** [comment]
This is not urgent. Let's firstly make new "merge" tests and then make sure that they pass with this.

**Comment by dkolistratova** [comment]
@ifilippov , Current tests pass, it shouldn't change anything - just simplified syntax.

**Comment by ifilippov** [comment]
If new merge test pass - then you can merge.

**Pull request merged**
